### ISSUE TITLE
Inquiry: average number of ships

### ISSUE THREAD

**Issue by patrickpatrickxwing** [AlexRaubach/MetaWing#11]
I was wondering if you could assist with confirming or disproving a data point in my pace of play findings.  Can you calculate the average number of ships being taken?  I am wondering if it is around 4?  If it is not possible it is ok, just confirming a curiosity.

**Comment by mwhited** [comment]
@patrickpatrickxwing It's not something I can calculate off hand with MetaWing, but you can hit listfortress.com/api/v1/tournaments API and listfortress.com/api/v1/tournaments/{id} API to pull the information and do a calculation like that of the data.
