### ISSUE TITLE
Bulk Export Option?

### ISSUE THREAD

**Issue by sethltaylor** [AlexRaubach/MetaWing#18]
Right now you can export individual lists by clicking export and copy pasting the XWS or exporting as JSON. However, I know many players are interested in data such as average bid, which could be calculated from the XWS. Is it possible to develop an option to bulk export the XWS for all of the lists?

**Comment by AlexRaubach** [comment]
All the data used in Metawing comes directly from ListFortress via its API. If you want to parse through all the lists between certain date ranges, using the List Fortress API is the way to go. 

If that API needs to be added to or updated, I'd be happy to work on that, but I don't want to duplicate the existing work.
