### ISSUE TITLE
iOs Menu problem

### ISSUE THREAD

**Issue by lartem12** [AlexRaubach/MetaWing#46]
I am able to reach the website, but the menus are not accessible. I cant change filters, or reach the menu where I can search for pilots or ships. 

I am using iphone se2 tried it on safari and firefox, and it was working before.

**Comment by AlexRaubach** [comment]
Thanks for the bug report. I updated the version of bootstrap metawing uses not that long ago. I bet that the classes used to decided when to show those menus changed and now they're no longer visible. Should be a pretty easy fix, I'll try to look into it this weekend.

**Comment by AlexRaubach** [comment]
Yeah, just what I thought. Fixed in 811f068

**Comment by lartem12** [comment]
You are awesome!

Thank you
