### ISSUE TITLE
Preset dates update

### ISSUE THREAD

**Issue by Keriganed** [AlexRaubach/MetaWing#6]
Hi there. I've seen the preset dates have not been updated in a while, so I would like to request if it can be done. It's missing dates like wave 5 realease (2020-09-13), points update (2020-01-20) and wave 6 (2020-01-31).

Best regards,
Leo.

**Comment by AlexRaubach** [comment]
The filter should now be up to date. Thanks for the push to update this and for including the dates in your request.

The changes are in commit bb9226693ff96c6701312f57596302d702c704d6
