### ISSUE TITLE
Not an issue but a request: Player Ranking

### ISSUE THREAD

**Issue by JediOswald** [AlexRaubach/MetaWing#60]
MetaWing already has pilot, ship, and archetype rankings but it would be neat to have a player ranking and sort the other rankings with this data factored into account. You don't need to do this, just an idea to add even more functionality to the site!

**Comment by mwhited** [comment]
I actually thought about this, but without having players consistently
entering the same username or other unique identifier it gets really hard
to associate them. There also isn't an easy way to prevent someone from
pretending to be a player to affect their ranking.

**Comment by JediOswald** [comment]
That makes sense. Maybe it will be easier with chaincode? The other reason I suggest this is that some builds have higher skill floors than newer players' skill levels, so it could make friendly builds easier for them to find. For a pre-2.5 example, if someone wants to fly Anakin, would Anakin Obi Ashoka be easier or Supernatural Regen Anakin + 1 gold squadron trooper torrent? Though I get where you're coming from, it is difficult to regulate.
Hope you have a fantastic day!
