### ISSUE TITLE
2.5 Standard filter ?

### ISSUE THREAD

**Issue by brunopugliese** [AlexRaubach/MetaWing#61]
In archetypes, I can't filter by 2.5 Standard formats. Is it planned to be added?

**Comment by relatifnaturel** [comment]
Came here to ask this, was wandering if a little up was welcome :)

**Comment by AlexRaubach** [comment]
I made a change in ListFortress to allow users to separate out 2.5 tournaments from 2.0 but never got around to fixing metawing. Luckily, all I had to do was add a name to the format objects in the db and they get populated in the filter bar dropdowns automatically.

**Comment by relatifnaturel** [comment]
You're a star! Thank you for that and all the rest :)
