### ISSUE TITLE
Swivel wing image is missing

### ISSUE THREAD

**Issue by NyarlathotepZERO** [AlexRaubach/MetaWing#66]
(As per title) 

![image](https://user-images.githubusercontent.com/26475624/191629921-d3024ccc-e9b2-402b-be92-c93eec467eeb.png)

![image](https://user-images.githubusercontent.com/26475624/191629893-9044a19f-8855-4f4c-9111-2e738b523dbd.png)

**Comment by AlexRaubach** [comment]
I've since switched to using the image links inside xwing data to get card images. If a card image is missing or the link doesn't work, please make a pull request there https://github.com/guidokessels/xwing-data2 to fix it and the changes will be pulled into metawing within 24 hours.
