### ISSUE TITLE
Improving xwingdata2 importing

### ISSUE THREAD

**Issue by AlexRaubach** [AlexRaubach/MetaWing#9]
Currently, xwingdata2 is a git submodule and is manually imported by updating the submodule, uploading the entire repo to heroku via cli to include the submodule and then running the rake task xwing-data2 which calls [this function.](https://github.com/AlexRaubach/MetaWing/blob/master/app/models/importers/xwing_data2.rb). 

If xwingdata2 could be imported directly from github then the entire process could be automated and run weekly. This is important because tournaments with new cards aren't imported at all which means reimporting old tournaments after the xwingdata2 is finally run etc.

**Comment by mwhited** [comment]
I'll look at this next, but we might have an issue here when they make a change to a pilot, especially when the slots change, I don't know if it cleans up those slots.
